services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - dbor
    ports:
      - "3006:3001"
    environment:
      # - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:Siiq@0026@db:5432/or25
      - JWT_SECRET=5c0841a288e4e48bf1d52ca10671baa6556a5251
      - JWT_EXPIRES_IN=24h
      - PORT=3001

    restart: always

  frontend:
    build:
      context: ./Front
    networks:
      - dbor
    ports:
      - "8085:80"
    depends_on:
      - web
    restart: always


  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Siiq@0026
      - POSTGRES_DB=or25
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dbor


networks:
  dbor:
    driver: bridge

volumes:
  postgres_data: