services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3006:3001"
    environment:
      # - NODE_ENV=production
      - DATABASE_URL="postgres://postgres:Siiq@0026@dbor25:5433/or25"
      - JWT_SECRET="5c0841a288e4e48bf1d52ca10671baa6556a5251"
      - JWT_EXPIRES_IN="24h"
      - PORT=3001

    restart: always

  frontend:
    build:
      context: ./Front
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always


  dbor25:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Siiq@0026
      - POSTGRES_DB=or25
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  postgres_data:
